version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-23
      - test-24

erlang-test-steps: &erlang-test-steps
  steps:
    - run:
        name: install units
        command: sudo apt install units
    - checkout:
        path: ~/repo
    - run:
        name: run tests
        command: make tests
        working_directory: ~/repo
    - run:
        name: run dialyzer
        command: make dialyze
        working_directory: ~/repo

jobs:
  test-23:
    <<: *erlang-test-steps
    docker:
      - image: circleci/erlang:23
  test-24:
    <<: *erlang-test-steps
    docker:
      - image: circleci/erlang:24
