version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-24
      - test-25

erlang-test-steps: &erlang-test-steps
  steps:
    - run:
        name: install units
        command: sudo apt update && sudo apt install -y units
    - checkout:
        path: ~/repo
    - run:
        name: run tests
        command: make tests
        working_directory: ~/repo
    - run:
        name: run dialyzer
        command: make dialyze
        working_directory: ~/repo

jobs:
  test-24:
    <<: *erlang-test-steps
    docker:
      - image: cimg/elixir:1.13-erlang-24.3
  test-25:
    <<: *erlang-test-steps
    docker:
      - image: cimg/elixir:1.13-erlang-25.0.3
