name: release

on:
  push:
    tags:
      - **

jobs:
  create-release:
    runs-on: ubuntu-20.04 # same as ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Erlang
        uses: gleam-lang/setup-erlang@1.1.2
        with:
          # https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_24.0.1-1~ubuntu~focal_amd64.deb
          otp-version: 24.0.1
      - name: Test
        run: rebar3 ct
      - name: Create release
        run: rebar3 release
      - name: Create release archive
        run: tar -czf rinseweb.tar.gz -C _build/default/rel .
      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          files: rinseweb.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
