name: release

on:
  push:
    tags:
      - '**'

jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3
          rebar3-version: 3
      - name: Install units
        run: sudo apt install units
      - name: Test
        run: rebar3 ct
      - name: Create release
        run: rebar3 release
      - name: Create release archive
        run: tar -czf rinseweb.tar.gz -C _build/default/rel .
      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          files: rinseweb.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
