name: test

on:
  push

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Erlang/OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['26.0', '27.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: 3
      - name: Install units
        run: sudo apt install units
      - name: Run tests
        run: make tests
      - name: Run dialyzer
        run: make dialyze
