name: test

on:
  push

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['24.3', '25.3']
    steps:
      - name: Get latest rebar3
        run: curl -sSL -o ~/bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3 && chmod +x ~/bin/rebar3
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - name: Install units
        run: sudo apt install units
      - name: Run tests
        run: make tests
      - name: Run dialyzer
        run: make dialyze
